#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         File-Headerinfo
version:      0.03
version_from: lib/File/Headerinfo.pm
installdirs:  site
requires:
    Image::Size:                   0
    SWF::Header:                   0
    MP3::Info:                     0
    Audio::Wav:                    0
    Video::Info:                   0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
